### ISSUE TITLE
Receiving screen cast byte[] on a browser

### ISSUE THREAD

**Issue by shubendrak** [Temasys/skylink-android-screen-sharing#1]
With android device you are sending byte[], my question is how can i receive and show it in my web browser

**Comment by janiduw** [comment]
At the moment SkylinkJS does not have binary only data sending support. This is something planned for the future. For the moment the work around is to convert the images to base64 and send using the sendP2PMessage.

**Comment by adityask02** [comment]
After opening the app i am getting the tost message onConnection False.
