### ISSUE TITLE
Frame Rate evaluation

### ISSUE THREAD

**Issue by Raj123456788** [Temasys/skylink-android-screen-sharing#2]
Have  you guys tested the frame rate on different platform. Reading would be helpful.

**Comment by Raj123456788** [comment]
Can anyone answer my questions?

**Comment by goddino** [comment]
Hi Raj123456788,
This sample was meant as a simple and interesting demonstration of the usage of the Skylink for Android SDK's SkylinkConnection.sendData API.
It was not meant to interop with any other Apps or platforms.
